### ISSUE TITLE
unable to install/activate oc8.1

### ISSUE THREAD

**Issue by Lebernd** [juliushaertl/direct_menu#10]
when I try to activate the app I get:

`cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html`

The site tells me:

`Peer certificate cannot be authenticated with known CA certificates.`

Installation with `git clone` works fine

**Comment by juliusknorr** [comment]
There was an issue with the certificate chain, on the server that is hosting the .zip file.
Can you retry again?

**Comment by Lebernd** [comment]
It's working :ok_hand:
