### ISSUE TITLE
OC 8.2.1 not compatible to direct menu 0.4

### ISSUE THREAD

**Issue by FrankMaute** [juliushaertl/direct_menu#15]
Hello,

when activating direct menu on 8.2.1 the Admin/personal menu does not show up. Can you help?

Thanks in advance,
Frank.

**Comment by juliusknorr** [comment]
Thanks, the fix has already been provided by #14

**Comment by FrankMaute** [comment]
Hi Julius,

thanks, works!

Frank.

Quoting Julius Härtl notifications@github.com:
