### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/direct_menu#16]
I use OC 8.2 and I wanted to upgrade to the current version 0.5, which produces the following error message See enclosed screen shot! 
What went wrong??
![directmenue](https://cloud.githubusercontent.com/assets/9738727/11238666/831299f6-8de7-11e5-9bc5-e4aa4d837eda.png)
 regards, hitam4450

**Comment by juliusknorr** [comment]
Could you try again? It seems like there was an issue with the new ssl certificate on the server providing the zip file.

**Comment by hitam4450** [comment]
OK, it worked now! Many Thanks!
