### ISSUE TITLE
Incomplete View in OC'version' => '8.2.1.4'

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/direct_menu#18]
Please check:

https://github.com/owncloud/core/issues/20631

regards, hitam4450

**Comment by juliusknorr** [comment]
Have you updated direct_menu to the current version 0.5?
This has already been fixed in #14

**Comment by hitam4450** [comment]
Yes, this happened wit direct_menu 0.5! Sorry!

**Comment by hitam4450** [comment]
Ok, reinstalling the app and enabling it - resolved the problem!
Many Thanks!
regards, hitam4450
