### ISSUE TITLE
Menu Bar icons move with main screen in Safari on iPad

### ISSUE THREAD

**Issue by JonesfromHan** [juliushaertl/direct_menu#19]
I just saw this happen on my iPad.
### Steps to reproduce
1. Open ownCloud with installed direct menu in Safari on an iPad
2. Move the page with your finger
### Expected behaviour

The icons should stick to their place on the menu bar
### Actual behaviour

The icons move with the page
### Server configuration

**ownCloud version: 8.2.2**

**Plugin Version: 0.6**
### Client configuration

**Browser: Safari**

**Operating system: iOS 9.2.1 on iPad 2**

I could only test it on an iPad, i don't know how other Browsers will act.

![photo-2016-01-28-20-13-38_0279](https://cloud.githubusercontent.com/assets/8125717/12656067/78e66b0e-c5fc-11e5-96d0-3037501bc3a2.PNG)
![photo-2016-01-28-20-13-42_0280](https://cloud.githubusercontent.com/assets/8125717/12656066/78e03b30-c5fc-11e5-8e1a-5ba4fcc619c0.PNG)
![photo-2016-01-28-20-13-46_0281](https://cloud.githubusercontent.com/assets/8125717/12656065/78dc345e-c5fc-11e5-93ff-e0962a3d0ba6.PNG)

**Comment by juliusknorr** [comment]
Thanks for your report. I can reproduce this on android using firefox. I'll look into this.

**Comment by JonesfromHan** [comment]
This fixed it for my iPad, I hope it works on other devices, too.
