### ISSUE TITLE
[Feature Request] Changing order of Icons

### ISSUE THREAD

**Issue by dynobo** [juliushaertl/direct_menu#23]
Please add a possibility to rearrange the icons. This would be very useful to me, with > 8 Apps...

Thanks for this app! :-)

**Comment by juliusknorr** [comment]
I already thought about this, but as there is no dynamic mechanism in owncloud core to update the app order, I decided not to implement reordering. 
This feature was also requested and rejected in core: https://github.com/owncloud/core/issues/10654 

You can manually edit the order parameter for each app inside the app.php file to achieve a custom order:

```
\OCP\App::addNavigationEntry(array(
    //...
    'order' => 10,
```

**Comment by Mannshoch** [comment]
This will end in an Integrity error after upgrading Owncloud and also it went to default position if an App get updated.

**Comment by juliusknorr** [comment]
I've just started implementing the ability to reorder app icons. See #28

**Comment by Mannshoch** [comment]
Thanks a lot @juliushaertl

**Comment by juliusknorr** [comment]
See https://github.com/juliushaertl/apporder for ongoing progress.
