### ISSUE TITLE
Style of App-Name broken

### ISSUE THREAD

**Issue by aspdye** [juliushaertl/direct_menu#24]
Currently, the name of the app currently running is displayed in the way ownCloud does with its normal menu. I don't know why, but I think we should change that :grin: 
The app name is too small, and its position is a bit strange.

**ownCloud 9.0.0**

**Comment by juliusknorr** [comment]
Can you describe a bit more what you have in mind.
I don't see any reason to change the positioning at the moment, for me this looks quite nice.

**Comment by juliusknorr** [comment]
@aspdye ping

**Comment by aspdye** [comment]
I think we should use the same font (and size of it) of the normal menu :wink:

**Comment by juliusknorr** [comment]
Ah now I get it, good point.

**Comment by aspdye** [comment]
:+1:
