### ISSUE TITLE
showing app title does not work with owncloud 0.8.2

### ISSUE THREAD

**Issue by horstk** [juliushaertl/direct_menu#3]
Hi,

version 0.2 works perfectly with owncloud 7.05, but with 0.8.2 app titles will never be shown ( neither when hovering over an app nor when selecting an app) 

Regards

Horst

**Comment by juliusknorr** [comment]
That is strage, as on my 8.0.2 owncloud instance it works quite well. Could it be a caching issue? Have you tried to disable and reenable the app?

**Comment by horstk** [comment]
I tried everything. I deinstalled the app, deleted the entries in mysql,
and installed it again.
Then I used a brand new installation of firefox, but still: it works
with 7.0.5 but not with owncloud 0.8.2

Am 31.03.2015 um 12:44 schrieb Julius Härtl:

**Comment by juliusknorr** [comment]
Can you proove that the css file `direct_menu.css` is loaded and contains the rule `#navigation div li:hover span` ?

**Comment by horstk** [comment]
Now it works.
I moved the old "direct_menu" directory in the main "owncloud" directory
to park it while testing version 0.2 . Nevertheless owncloud did take
the old "direct_menu.css" from the old directory. Deleting it solved the
problem

Thanks

Horst

Am 31.03.2015 um 16:07 schrieb Julius Härtl:

**Comment by juliusknorr** [comment]
Ok, fine.
