### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MorrisJobke** [juliushaertl/direct_menu#30]
http://choosealicense.com/

At least AGPL and MIT are compatible with ownCloud/Nextcloud.

**Comment by juliusknorr** [comment]
Ah good point, the AGPL is only stated in the info.xml. Will add that later today.

**Comment by MorrisJobke** [comment]
> Ah good point, the AGPL is only stated in the info.xml. Will add that later today.

I was just curious. Otherwise this software can't be used together with ownCloud/Nextcloud due to the APGL which forbids to run together with proprietary software.
