### ISSUE TITLE
icons not always shown with Nextcloud 10 RC1

### ISSUE THREAD

**Issue by Guillaume99** [juliushaertl/direct_menu#33]
icons not always shown with Nextcloud 10 RC1

![capture d ecran 2016-08-20 a 18 08 16](https://cloud.githubusercontent.com/assets/20171421/17832611/a4d19660-6707-11e6-947b-261c359b3a84.png)
![capture d ecran 2016-08-20 a 18 08 31](https://cloud.githubusercontent.com/assets/20171421/17832610/a4d0016a-6707-11e6-86e5-e981cb137e40.png)

**Comment by juliusknorr** [comment]
@Guillaume99 what version of direct_menu and what  web browser are you using?

**Comment by Guillaume99** [comment]
Last version of direct menu (updated for nc 10), 
Last version of firefox under osx

**Comment by juliusknorr** [comment]
Ok, will try to reproduce and fix this later this week. Thanks for your report so far.

**Comment by Guillaume99** [comment]
For my specific case, what should I change innthe css file ?

**Comment by juliusknorr** [comment]
You can change the min-width value in the first line to something bigger. 

e.g. the menu will be hidden if the window size is smaller that 900 px:
`@media only screen and (min-width: 900px) {`

**Comment by Guillaume99** [comment]
Thanks !

**Comment by juliusknorr** [comment]
@Guillaume99 Can you please test if your issue still exists?

**Comment by Guillaume99** [comment]
Tested and validated, issue is corrected.
Thanks for the good work !

**Comment by car-gli** [comment]
Wrong thread, sorry
