### ISSUE TITLE
Wrong Version 0.91 in appstore should be 0.92

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/direct_menu#39]
Sorry, for my feedback! In th appstore th wrong version number shows in the "**latest**" app name!

regards, hitam4450

**Comment by juliusknorr** [comment]
Thanks. Fixed.

Can't wait to finally use the Nextcloud store ... makes publishing so much easier. :smile:

**Comment by hitam4450** [comment]
Ok, no problem! I wait as well for the Nextcloud App Store! However the future will be bright & better!

regards, hitam4450
