### ISSUE TITLE
direct menu doesn't work properly if an own theming is used

### ISSUE THREAD

**Issue by scroom** [juliushaertl/direct_menu#4]
As described above. I wanted to activate my own theming on Owncloud but then direct menu did not work. Beneath the top bar a little window with my activated apps have been shown. Didn't work with an old theme and a fresh one.
Here comes a screenshot:
https://cloud.githubusercontent.com/assets/5347731/6899691/63ef33aa-d702-11e4-855b-a763f9d6e15e.png

**Comment by juliusknorr** [comment]
I'm not using themes. Do you have an example that would helpme to debug this issue?

**Comment by scroom** [comment]
I've just copied the relevant parts of core to a theming folder. Following the Owncloud documentation (https://doc.owncloud.org/server/8.0/admin_manual/operations/theming.html) these are the folder css, img and js. Then I've activated the theme by adding the name in the config.php. Thats all.
The app didn't work with a "fresh" theme and an old one.

**Comment by juliusknorr** [comment]
The problem might be that you copied the whole header.css file. Owncloud is loading this file after direct_menu.css and the rules for the menu get overwritten.

I'll try to fix that in the next release. Until then you might want to remove the content of header.css in your template except the parts you've changed from default.

This is also better for your page loading time. There is no need for doubled css rules. ;-)

**Comment by juliusknorr** [comment]
Some issue on custom themes is fixed in master now, the background color will not be overwritten by direct_menu. 

@alex42ka are you sill having issues?
