### ISSUE TITLE
Application names has been moved?

### ISSUE THREAD

**Issue by matt407** [juliushaertl/direct_menu#41]
I did an update to version 8.2.8 of Owncloud and saw that the application names is moved to the right. 
Is a patch of this behaviour possible on direct_menu 0.5? 
Owncloud 8.2.8 with direct_menu Version 0.5 is in use.

![direct_menu_screenshot](https://cloud.githubusercontent.com/assets/8255606/18712404/8e7c71da-800e-11e6-9344-12f933cbc9d3.jpg)

**Comment by juliusknorr** [comment]
0.5 is quite old. You could update to 0.8.0 which should still support owncloud 8. No idea what's going on there, as i don't have any owncloud instance running.

**Comment by juliusknorr** [comment]
@matt407 Sorry for the delay, btw. :see_no_evil:

**Comment by matt407** [comment]
Thank you for your reply, where can version 0.8 be found? Under your releases only are 0.9x and v0.1 available.

**Comment by juliusknorr** [comment]
Ah sorry, I've forgot that I started publishing to GitHub with version 0.9.0.

You can basically download the archive for the commit of 0.8.0 version here:
https://github.com/juliushaertl/direct_menu/archive/37937f2dd29aa7a0f8538a73940698802e7e1486.zip

**Comment by matt407** [comment]
0.8.0 works fine! thank you!
