### ISSUE TITLE
Nextcloud 10 / Notifications not clickable

### ISSUE THREAD

**Issue by DemoFreak** [juliushaertl/direct_menu#42]
With direct_menu enabled the notifications icon isn't clickable (maybe overlayed by the menu).
Please see the attached pictures (note the mouse pointer shape).

![with_directmenu](https://cloud.githubusercontent.com/assets/9294774/19831756/0a869ba4-9e12-11e6-9940-6ddcf9faae41.png)

![wo_directmenu](https://cloud.githubusercontent.com/assets/9294774/19831757/0e0d6b18-9e12-11e6-84ec-aa7e443d03e3.png)

Feel free to tell me where I could help testing, or if I should provide additional information.

regards,

Hannes

**Comment by juliusknorr** [comment]
@DemoFreak This is not the position where the notification icon should be. It should look more like this:
![2016-10-29-205748_321x79_scrot](https://cloud.githubusercontent.com/assets/3404133/19832082/a2d8c15e-9e1a-11e6-96d5-d65a063b7d1c.png)

Do you use any other modifications/custom patches?

What version of the direct_menu / notifications app do you use?

**Comment by DemoFreak** [comment]
@juliushaertl No modifications/patches that I'm aware of. 
occ app:list shows

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - direct_menu: 0.9.2
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - imprint: 0.2.5
  - logreader: 1.1.5
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - piwik: 0.1.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_mv
  - files_retention
  - user_ldap
  - user_saml
```

**Comment by juliusknorr** [comment]
@DemoFreak  Can you check if the following commands return any output:

<code>
./occ integrity:check-core
./occ integrity:check-app notifications
</code>

Are you using Nextcloud 10.0.1?

**Comment by DemoFreak** [comment]
@juliushaertl both commands return with no output.
I'm still using NC 10.0:

```
occ status
  - installed: true
  - version: 9.1.0.16
  - versionstring: 10.0
  - edition: 
```

**Comment by juliusknorr** [comment]
Ok, it looks like you are still using some prerelease of Nextcloud 10. Can you upgrade to the latest stable release 10.0.1 ?

My guess is that this will fix wrong positioning of the notifications icon, so this is out of scope of the direct_menu app, so I'm closing this for now. Feel free to ask if there are questions left.

**Comment by DemoFreak** [comment]
Manually updated NC to 10.0.1, but the problem persists.

```
occ status
  - installed: true
  - version: 9.1.1.5
  - versionstring: 10.0.1
  - edition: 
```

```
occ app:list
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - imprint: 0.2.5
  - logreader: 1.1.5
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - piwik: 0.1.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_ldap
  - user_saml
```

**Comment by juliusknorr** [comment]
@DemoFreak So the notifications icon is still in the wrong place? What browser are you using?

**Comment by DemoFreak** [comment]
Firefox (now on version 50.0)
