### ISSUE TITLE
Does not work on Nextcloud 11 beta

### ISSUE THREAD

**Issue by Revertron** [juliushaertl/direct_menu#44]
Unfortunately, it does not work on Nextcloud 11 beta.
If you can tell me how can I investigate it further, I will be glad to do so.

Thanks in advance! It is an important app for Nextcloud!

**Comment by juliusknorr** [comment]
@Revertron Thanks for your report. The issue has been fixed with a547d3e5f7db4fed8746be6abea604e33b0e4bd5 and a new release has been pushed to the Nextcloud appstore.

**Comment by mightyBroccoli** [comment]
You are the greatest. Thank you this app is essential to use nextcloud owncloud what ever :D

**Comment by juliusknorr** [comment]
Thank you very much @mightyBroccoli :smile:
