### ISSUE TITLE
Adjust name popover width to app name

### ISSUE THREAD

**Issue by jancborchardt** [juliushaertl/direct_menu#47]
Currently when hovering the app icon, all the popover widths are the same. It looks a bit strange and not polished. Instead can we adjust it so they fit the content perfectly, like with the dark tooltips?

I played very briefly with the CSS and adjusting the one `min-width: 120px` seems to break. I assume you also checked that @juliushaertl? cc @eppfel @skjnldsv

**Comment by skjnldsv** [comment]
Because margin-left is fiixed.
If you want to center an undecided width, you need to use `transform: translateX(-50%);` instead of `margin-left: -60px;` (line 105) 😃

**Comment by juliusknorr** [comment]
Good point @jancborchardt 
I've added this in #49 

Thanks for the transform hint @skjnldsv

**Comment by jancborchardt** [comment]
Hehe you were faster, I was about to do this ;)
