### ISSUE TITLE
Unset color inversion

### ISSUE THREAD

**Issue by mcnesium** [juliushaertl/direct_menu#52]
![bildschirmfoto 2016-12-22 um 19 38 52](https://cloud.githubusercontent.com/assets/476060/21436824/ba052cb0-c880-11e6-9ed0-517f42c84348.png)

The inverted color does not look too good with everything else not being inverted.
Is there a config setting to make it not do that?

**Comment by eppfel** [comment]
That looks like an older nextcloud version, which one you are using? Normally the inversion should be in the rest of nextcloud as well.

**Comment by mcnesium** [comment]
It's a brand new nc 11.0.0 and direct menu 0.9.3

**Comment by juliusknorr** [comment]
@mcnesium Have you cleared your browser cache? I guess we need to add some cachebuster value to the css url.

**Comment by juliusknorr** [comment]
@mcnesium Btw. the folder icons in the files app should have the same color as your menu bar since Nc 11. That looks like a bug here as well. Can you check if there are files in `data/appdata_XXX/theming/XX/`?

**Comment by mcnesium** [comment]
Same thing in different browsers, so propably not a browser cache issue. I cleared the entire cache in one browser to check.

This is how the directory looks like:
![bildschirmfoto 2016-12-24 um 13 10 45](https://cloud.githubusercontent.com/assets/476060/21466939/74bdb004-c9da-11e6-8c51-7b7859830d8a.png)
folder-public and -shared are orange as well, only the default folder is still blue.

**Comment by juliusknorr** [comment]
@mcnesium can you check if the color inversion works with the changes committed in 3a25cf1e137d322882dd268496271ad33ae4526c 

It is rather strange that only some folder icons have the correct color. Are there any errors in the server log files?

**Comment by mcnesium** [comment]
updated to 0.10.0 and now it looks like this on the orange instance:

![screenshot from 2017-01-11 14-16-42](https://cloud.githubusercontent.com/assets/476060/21849984/c4a2352c-d808-11e6-9f33-84519a425605.png)

on another instance with darker background color it looks fine like this:

![screenshot from 2017-01-11 14-16-55](https://cloud.githubusercontent.com/assets/476060/21849983/c481114e-d808-11e6-8676-2f9fc5cfce60.png)

As the orange one is hosted on an FTP-only hosting platform, I can only provide logs accessible from the nc-admin log page:

    Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#218	2017-01-11T14:00:47+0100
    Error	PHP	fread() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#217	2017-01-11T14:00:47+0100
    Error	PHP	fopen(/www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-settings): failed to open stream: No such file or directory at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#216	2017-01-11T14:00:47+0100
    Error	PHP	filesize(): stat failed for /www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-settings at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#211	2017-01-11T14:00:47+0100
    Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#218	2017-01-11T14:00:44+0100
    Error	PHP	fread() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#217	2017-01-11T14:00:44+0100
    Error	PHP	fopen(/www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-settings): failed to open stream: No such file or directory at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#216	2017-01-11T14:00:44+0100
    Error	PHP	filesize(): stat failed for /www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-settings at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#211	2017-01-11T14:00:44+0100
    Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#218	2017-01-11T14:00:43+0100
    Error	PHP	fread() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#217	2017-01-11T14:00:43+0100
    Error	PHP	fopen(/www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-files): failed to open stream: No such file or directory at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#216	2017-01-11T14:00:43+0100
    Error	PHP	filesize(): stat failed for /www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-files at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#211	2017-01-11T14:00:43+0100
    Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#218	2017-01-11T14:00:34+0100
    Error	PHP	fread() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#217	2017-01-11T14:00:34+0100
    Error	PHP	fopen(/www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-files): failed to open stream: No such file or directory at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#216	2017-01-11T14:00:34+0100
    Error	PHP	filesize(): stat failed for /www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-files at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#211	2017-01-11T14:00:34+0100
    Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#218	2017-01-11T14:00:12+0100
    Error	PHP	fread() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#217	2017-01-11T14:00:12+0100
    Error	PHP	fopen(/www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-core): failed to open stream: No such file or directory at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#216	2017-01-11T14:00:12+0100
    Error	PHP	filesize(): stat failed for /www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-core at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#211	2017-01-11T14:00:12+0100
    Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#218	2017-01-11T14:00:09+0100
    Error	PHP	fread() expects parameter 1 to be resource, boolean given at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#217	2017-01-11T14:00:09+0100
    Error	PHP	fopen(/www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-core): failed to open stream: No such file or directory at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#216	2017-01-11T14:00:09+0100
    Error	PHP	filesize(): stat failed for /www/htdocs/xxxxx/data/appdata_ochd9io7qveg/theming/0/favIcon-core at /www/htdocs/xxxxx/nextcloud/lib/private/Files/Storage/Local.php#211

**Comment by mcnesium** [comment]
Maybe it has something to do with [disabling the theming app](https://github.com/nextcloud/server/issues/3094#issuecomment-273425207), but now it looks alright:

![bildschirmfoto 2017-01-20 um 17 44 36](https://cloud.githubusercontent.com/assets/476060/22157477/2b91a6ce-df38-11e6-82f2-964c210ffe9a.png)
