### ISSUE TITLE
works not in 10.0.3

### ISSUE THREAD

**Issue by blackcrack** [juliushaertl/direct_menu#54]
Hi Julius,

have downloaded your master because the version had not work
on 9.2 , i have php 7.0 and NC 10.0.3... downloaded your actual master.zip, so 
your version 10 (bump 10 or someting) and overwrite the 9.2.. it works also not..  :\
can it be possible ?

best regards
Blacky

**Comment by juliusknorr** [comment]
@blackcrack Thanks for reporting. I'll have a look, are there any errors in the server/browser log?

**Comment by blackcrack** [comment]
hi Julius, 
there was a automatic hiding *ghnnnnn* and i be at moment 
on the way with my laptop, so, no problem with work, but an other problem, 
if you can change the css-style a bit..
I have create a theme for nextcloud (btw. i hope it works also in OC)
and the problem/conceptual formulation/task ;) it is , to be your menu not direcktly over the files, it hangs up to the "application-name" and if whant this skining, it is not really possible, btw it is to view to be your direct-menu hanging really left sided... if you try the theme by include in config.php at last entry,
do you see what i meant. ;)
http://blackysgate.net/files/upload/owncloud/neXtrealTime.v0.8.tar.gz 
have fun by try it out :)
and i guess it is not bad for night hawk eyes ;)
i want later change the icons too..

best regards
Blacky

**Comment by juliusknorr** [comment]
Hi, sorry I've forgot to have a look, but I'll try to have a look this week. Or is #55 already fixing the issue for you?

**Comment by juliusknorr** [comment]
I just had a look at the theme. If i understand you correctly this is what you try to achieve, right?
![2017-03-16-114212_602x106_scrot](https://cloud.githubusercontent.com/assets/3404133/23992575/b0fbbad6-0a3d-11e7-90ef-e59e18248ee4.png)

It should work fine if you add the following rules to your theme css code:
```
#navigation div ul {
  padding-right: 10px !important;
  margin-left: 0 !important;
  }
div#navigation.menu {
  margin-left: 170px;
}
```

Anyway, this is not an issue with direct_menu :wink:, so I'm closing this.
