### ISSUE TITLE
Direct Menu kills OPDS Catalog

### ISSUE THREAD

**Issue by stormsh** [juliushaertl/direct_menu#56]
Hi, I am using nc 11.0.1 on ubuntu 14.04 with php 7.0.16. I had my opds catalog (0.8.2) on a different site but fused them together just now. As soon as I activate Direct menu, the opds catalog becomes inaccessable. No way back but loading a db backup. 
The error is an xml parser error. The line differs between somewhat in the 80 to 98.

> XML-Verarbeitungsfehler: Nicht übereinstimmendes Tag. Erwartet: .
Adresse: https://mydomain.de/apps/files_opds/
Zeile Nr. 88, Spalte 8:

I don't know in which file the parser error appears. The opds catalog doesn't have a menu entry. You have to menually add the url to get there. Which might be the problem. I don't know.
I had that problem before but couldn't pin it to direkt menu until now.
I allready tried to give the info to the opds programer, but no luck. Maybe my info was not enough.

Thx 4 F1.
st.

**Comment by Yetangitu** [comment]
I'm the author of OPDS Catalog. I just checked the combination of OPDS Catalog and Direct menu on NC 11.0.0 and found out it worked for me. This is not surprising as Direct menu only changes the style sheet for the menu while OPDS Catalog does not use the menu at all (nor does it need to, being a remote service app).

I do use the full address to reach OPDS Catalog, including 'index.php'. As to whether that works or not depends on your web server configuration. Try it again, but this time using the full address:

   https://mydomain.de/index.php/apps/files_opds/

But... I guess there is something else amiss here, unrelated to OPDS Catalog or Direct menu - at least not to the actions of the apps themselves.

Which database do you use?

**Comment by stormsh** [comment]
Hi, I'm using mysql 5.5.54.
The url was a mistake, I'm using already the full URL including index.php.
Nevermind...
Thanks for your effords
