### ISSUE TITLE
missing changelog for 0.10.2

### ISSUE THREAD

**Issue by heinrichmartin** [juliushaertl/direct_menu#63]
0.10.2 is available, but the changelog does not contain information about the update. It is fine for me, if you just add details to this issue and to master. Release both changelog entries with the next tag (i.e. no need to bump the version because of missing changelog...).

**Comment by juliusknorr** [comment]
@heinrichmartin Sorry, I've missed to add those. I've updated the CHANGELOG on master.
The only change basically was to remove the old signatures file from the release archive, since it was breaking users instances when they upgrade to Nextcloud 12. Thanks for reporting. :+1:
