### ISSUE TITLE
Nextcloud 12

### ISSUE THREAD

**Issue by SchnorcherSepp** [juliushaertl/direct_menu#65]
Hi!

I know the DirectMenue is already present in the new version of NextCloud. 
BUT the Nextcloud version can only display 7 apps. The other apps are hidden behind points.

![zwischenablage03](https://cloud.githubusercontent.com/assets/14240880/26444787/17eec760-413e-11e7-9794-2f3cd82fbe79.jpg)

Can we have the old DirectMenue back please? ;)

**Comment by m4lvin** [comment]
This will be solved in the next release of Nextcloud, the limit was removed in https://github.com/nextcloud/server/pull/5135 :smile:

If you want the change immediately, just remove these lines from `core/js/js.js`: https://github.com/nextcloud/server/pull/5135/commits/65d52a1ddff74b58155b27e342caf30a554d62f5

**Comment by juliusknorr** [comment]
What @m4lvin said. :wink:
