### ISSUE TITLE
Nextcloud 12 : sig verif failed

### ISSUE THREAD

**Issue by Draky50110** [juliushaertl/direct_menu#66]
Hello.

Just updated to Newxtcloud 12 and I have an error about Direct Menu and invalid signature.

Here is logfile : 

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- direct_menu
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [direct_menu] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)

**Comment by JSoko** [comment]
Direct menue isn't Nc12-compatible, because it's integrted in Nc12...
...so just disable and delete it...

**Comment by Draky50110** [comment]
OMG, missed this new feature.
That explains why, once disabled, the direct menu was still present :p 

Thanks :)
