### ISSUE TITLE
direct_menu able to configuring in 2 way's

### ISSUE THREAD

**Issue by blackcrack** [juliushaertl/direct_menu#69]
Hi,

it should be able to configuring how many icons to let show up to be in an own menu moved
or maybe none icons where moved into an own pull-down menu, the decision about should be belong  by the user where use the menu icons.
also an sorting of the menuicons should be include, because both apps before was really nice in combination :)

best regards
Blacky

**Comment by juliusknorr** [comment]
Not happening. I won't put any further effort into development of this app, since the main functionality is now in nextcloud/server. :wink:

**Comment by blackcrack** [comment]
ah i remind, yes.. sorry.. :) .. i getting too old \*g\*
